server:
  port: 8080
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka 

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: employeeModule
        uri: lb://CLIENT-1-SERVICE
        predicates:
        - Path=/client/all
        filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 2
      - id: employeeModule
        uri: lb://CLIENT-1-SERVICE
        predicates:
        - Path=/client/**
        

    #   - id: consumerModule
    #     uri: lb://SECOND-SERVICE
    #     predicates:
    #     - Path=/consumer/**
